name: simple_financial_records
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  sqflite: ^2.3.1
  intl: ^0.19.0
  flutter_slidable: ^3.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

